---

# mention verison of postgres latest or required version 
postgresql_version: 9.6

pgSql_repo: 'deb http://apt.postgresql.org/pub/repos/apt/  xenial-pgdg main'

pgsql_key:  https://ftp-master.debian.org/keys/archive-key-6.0.asc

# its an default postgres user to acces pgsql
postgresql_admin_user: "postgres"

postgresql_database_name: Sample_DB

# Enable some options for streaming replication purposes
postgresql_database_user:
  name: cloudSeals
  pass: Cloud123@

# passing role attributes for user 
role_attr_user_flags: CREATEDB,NOSUPERUSER

# providing privilages for user
user_privilages: ALL

# pass the name to create database table 
DB_table_name: test_table

DB_table_columns: test varchar(100)


# dont not change the values this are fixed values 

postgresql_service_name: postgresql-{{ postgresql_version }}
postgresql_data_dir: /var/lib/postgresql/{{ postgresql_version }}/main
postgresql_data_backup_dir: /var/lib/postgresql/{{ postgresql_version }}/main_backup
postgresql_conf_dir: /etc/postgresql/{{ postgresql_version }}/main
postgresql_exec_dir: /usr/lib/postgresql/{{ postgresql_version }}/bin

postgresql_arch_dir: /var/lib/postgresql/{{ postgresql_version }}/main/archive

