---


# mention verison of postgres latest or required version 
postgresql_version: 10


pgSql_repo: https://oracle-apex-packages-repo.s3-us-west-1.amazonaws.com/PostgreSQL-Database/pgdg-redhat-repo-latest.noarch.rpm

# Enable some options for streaming replication purposes
postgresql_streaming_user:
  name: cloudSeals
  pass: Cloud123@



postgresql_initdb_name: postgresql{{ postgresql_version | replace('.', '') }}
postgresql_service_name: postgresql-{{ postgresql_version }}
postgresql_data_dir: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_data_backup_dir: /var/lib/pgsql/{{ postgresql_version }}/data_backup
postgresql_conf_dir: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_exec_dir: /usr/pgsql-{{ postgresql_version }}/bin

postgresql_arch_dir: /var/lib/pgsql/{{ postgresql_version }}/archive


masterIP: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"

masterIPS: "{% for host in groups['pg-master'] %}
            {{ hostvars[host]['ansible_facts']['eth0']['ipv4']['address'] }}
            {% endfor %}"

all_node_IPs: "{% for host in groups['pg-all'] %}
            {{ hostvars[host]['ansible_facts']['eth0']['ipv4']['address'] }}
            {% endfor %}"


postgresql_admin_user: "postgres"

postgresql_default_ipv4_auth_method: "md5"


postgresql_pg_hba_custom:
 - { type: host, database: replication, role: "{{ postgresql_streaming_user.name }}", address: "{{all_node_IPs}}/32", method: "{{ postgresql_default_ipv4_auth_method }}", comment: '' }

