  - name: install postgres repo
    yum:
      name: "{{pgSql_repo}}"
      state: present
  - name: Install Postgresql latest version
    yum:
      update_cache: yes
      name: "{{ item }}"
      state: present
    loop:
      - postgresql{{ postgresql_version |replace('.', '') }}
      - postgresql{{ postgresql_version |replace('.', '') }}-server
      - postgresql{{ postgresql_version |replace('.', '') }}-contrib
      - postgresql{{ postgresql_version |replace('.', '') }}-libs
      - python
  #    - python-pip
      - python-psycopg2
  - name: Initialize database
    shell: '{{postgresql_exec_dir | trim }}/{{postgresql_initdb_name | trim }}-setup initdb'
    when: postgresql_version <= 9.6
    ignore_errors: yes
  
  
  - name: Initialize database
    shell: '"{{postgresql_exec_dir}}"/postgresql-"{{postgresql_version}}"-setup initdb'
    when: postgresql_version >= 10
    ignore_errors: yes

  
  - name: Restart service postgresql, in all cases
    systemd:
      name: "{{postgresql_service_name}}"
      state: started
      enabled: yes
    
  - name: create DB
    become: yes
    become_user: "{{postgresql_admin_user}}"
    postgresql_db: 
      name: "{{postgresql_database_name}}"

  - name: Creating postgres user for "{{postgresql_database_name}}"
    become: yes
    become_user: postgres
    postgresql_user:
      db: "{{postgresql_database_name}}"
      name: "{{postgresql_database_user.name}}"
      password: "{{postgresql_database_user.pass}}"
      role_attr_flags: "{{role_attr_user_flags}}"
      priv: "{{user_privilages}}" 

  - name: Ensure we have access from the new user
    become: yes
    become_user: "{{postgresql_admin_user}}"
    postgresql_privs:
      db: "{{postgresql_database_name}}"
      role: "{{postgresql_database_user.name}}"
      objs: ALL_IN_SCHEMA
      privs: "{{user_privilages}}"

  - name: crating table in DataBase "{{postgresql_database_name}}"
    become: yes
    become_user: "{{postgresql_admin_user}}"
    postgresql_table:
      db: "{{postgresql_database_name}}"
      name: "{{DB_table_name}}"
      columns: "{{DB_table_columns}}" 
