



- hosts: all
  become: yes
  tasks:
  - name: Add repository
    yum_repository:
      name: MongoDB-Repository
      description: EPEL YUM repo
      baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
      gpgcheck: yes
      gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
      enabled: yes
  - name: Install a list of packages
    yum:
      name: mongodb-org
      state: present

  - name: Rum mangodb service
    systemd:
      name: mongod
      state: started
      enabled: yes
